export default function about() {

    const element = document.createElement('p')

    element.innerHTML = "<p>In the heart of our vibrant city lies a culinary sanctuary unlike any other – welcome to Trimmings Bistro. Here, we proudly redefine the essence of sustainable dining by exclusively crafting our dishes from vegetable trimmings and kitchen scraps. Prepare to be amazed as we transform humble scraps into culinary treasures, all under the expert guidance of our visionary head chef, Oliva – an esteemed microbiologist turned culinary virtuoso.</p>  <p>Step into our inviting space, where rustic charm meets contemporary flair, and embark on a gastronomic adventure that champions mindful eating and sustainability. As you peruse our menu, you'll be delighted to discover that every dish reflects our unwavering commitment to utilizing every last bit of nature's bounty. </p>  <p> Begin your journey with our Watermelon Rind Gazpacho, a refreshing symphony of flavors crafted from discarded watermelon rinds and heirloom tomatoes. Or, indulge in our Mushroom Stem Croquettes, where leftover mushroom stems are transformed into crispy bites of perfection, infused with aromatic herbs and spices. </p>    For the main course, immerse yourself in the vibrant fusion of Portuguese and Southern California cuisine with our Grilled Vegetable Espetada. Skewered vegetables, marinated in a zesty chimichurri sauce made from herb stems and citrus peels, showcase the artistry of utilizing every part of the plant. Alternatively, savor the essence of California with our Avocado Tacos, featuring creamy avocado slices nestled in warm tortillas and topped with a tangy salsa crafted from vegetable scraps.  <p> Save room for dessert, where our commitment to sustainability shines brightly. Indulge in our Chocolate Avocado Mousse, a velvety delight created from ripe avocados and cocoa bean husks, or cleanse your palate with our Citrus Sorbet, made from leftover citrus peels and sweetened with natural agave nectar. <p> At Trimmings Bistro, we invite you to join us in celebrating the beauty of plant-based cuisine and the magic of culinary innovation. With every bite, you'll not only savor exquisite flavors but also contribute to a more sustainable future. So gather your loved ones and immerse yourself in an unforgettable dining experience where every ingredient tells a story of sustainability, creativity, and culinary excellence."


    const content = document.querySelector('#content')

    content.appendChild(element)

}